# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LyO9dnjAu4T7xFX3lTcYAbe-zYq-uZa
"""

import numpy as np
import matplotlib.pyplot as plt

def mandelbrot(h=1000, w=1000, max_iter=200):
    x = np.linspace(-2.0, 1.0, w)
    y = np.linspace(-1.5, 1.5, h)
    C = x + y[:, None] * 1j
    Z = np.zeros_like(C)
    div_time = max_iter + np.zeros(C.shape, dtype=int)

    for i in range(max_iter):
        Z = Z**2 + C
        diverge = np.abs(Z) > 2
        div_now = diverge & (div_time == max_iter)
        div_time[div_now] = i
        Z[diverge] = 2

    return div_time

def generate_tshirt_graphic():
    image = mandelbrot(h=1200, w=1200, max_iter=200)

    fig, ax = plt.subplots(figsize=(10, 12), facecolor='black')
    ax.set_facecolor('black')

    ax.imshow(image, cmap="twilight_shifted", extent=[-2, 1, -1.5, 1.5])
    ax.axis("off")

    ax.set_title("Mandelbrot Set", fontsize=22, color="white", pad=20, fontweight="bold")

    python_code = (
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n\n"
        "def mandelbrot(h=800, w=800, max_iter=100):\n"
        "    x = np.linspace(-2.0, 1.0, w)\n"
        "    y = np.linspace(-1.5, 1.5, h)\n"
        "    C = x + y[:, None] * 1j\n"
        "    Z = np.zeros_like(C)\n"
        "    for i in range(max_iter):\n"
        "        Z = Z**2 + C\n"
        "    return Z\n\n"
        "plot_mandelbrot()"
    )

    ax.text(
        -1.9, 1.3, python_code,
        color="#00FFC8", fontsize=9, family="monospace",
        verticalalignment="top",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="black", alpha=0.7, edgecolor="#00FFC8")
    )

    plt.tight_layout()
    plt.savefig("mandelbrot_tshirt_print.png", dpi=300, facecolor=fig.get_facecolor(), edgecolor='none')
    plt.show()

generate_tshirt_graphic()